# Site settings
title: "Mohammad Hossein Niki Maleki"
email: "mh.nikimaleki@gmail.com"
baseurl: "https://imohammadhossein.github.io/" 
url: "" # the base hostname & protocol for your site

linkedin_username: "mhnikimaleki"
github_username: "imohammadhossein"

# Build settings
markdown: kramdown
