# Site settings
title: "Mohammad Hossein Niki Maleki"
email: "mh.nikimaleki@gmail.com"
baseurl: "https://imohammadhossein.github.io/" 
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:"imohammadhossein"

# Build settings
markdown: kramdown
